
import { COAExtractor } from '../services/coaExtractor';

async function testKCAExtraction() {
    console.log("🧪 Testing KCA Labs Extraction...");

    const extractor = new COAExtractor();

    // Mock Text simulating KCA Labs PDF content
    const mockText = `
KCA Laboratories
232 North Plaza Drive
Nicholasville, KY 40356

Client:
Low Gravity, LLC
203 Howe Road
Martinez, CA 94553
USA

Certificate of Analysis
1 of 8

Sample Information
Sample Type: Distillate
Sample ID: SA-231221-1234
Batch: BATCH-001
Received: 12/21/2023
Completed: 12/23/2023
Unit Mass (g): 11.5

Moisture Content
Moisture Content 12.5 %
Water Activity 0.55 aw

Cannabinoids by HPLC-PDA
Analyte LOD LOQ Result % Result mg/g
CBD 0.01 0.05 45.21 452.1
Delta-9-THC 0.01 0.05 0.23 2.3
Total Cannabinoids 45.44 454.4

Terpenes by HS-GC-MS/MS
Analyte LOD LOQ Result % Result mg/g
Beta-Myrcene 0.002 0.01 0.45 4.5
D-Limonene 0.002 0.01 0.12 1.2
Linalool 0.002 0.01 ND ND
Alpha-Pinene 0.002 0.01 0.08 0.8
Total Terpenes 0.65 6.5

Heavy Metals by ICP-MS
Analyte LOD LOQ Result
Arsenic 2 5 ND
Cadmium 1 5 ND
Lead 2 5 ND
Mercury 1 5 ND
Heavy Metals PASSED

Generated By: Alex Morris
Quality Manager
Date: 09/23/2025

Tested By: Nicholas Howard
Scientist
Date: 09/22/2025
`;

    // We can't easily mock the PDF buffer processing without a real PDF, 
    // but we can expose the private extract methods for testing or just mock the extractFromBuffer flow 
    // by sub-classing or extending, OR we just trust I implemented it right and use a real PDF if I had one.
    // However, I made the methods private.
    // I can modify the class to public for testing OR (better) I can just rely on `extractFromBuffer` 
    // IF I can pass a mock buffer and mock the `pdf(...)` call. 
    // But `pdf-parse` is external.

    // Allow me to use a trick: I will create a dummy buffer and mock the `pdf` function behavior 
    // if I was running a unit test framework. But here I am running a script.

    // Instead, I will use a tiny valid PDF buffer (empty) but I can't easily inject the text.

    // ALTERNATIVE: I will temporarily access the private methods via `any` casting for this test.

    console.log("--- Extracting Terpenes (Private Method Test) ---");
    const terpenes = (extractor as any).extractTerpenes(mockText);
    console.log("Terpenes Found:", terpenes.length);
    console.table(terpenes);

    console.log("--- Extracting Sample Info (Private Method Test) ---");
    const sampleInfo = (extractor as any).extractSampleInfo(mockText);
    console.log("Sample Info:", sampleInfo);

    console.log("--- Extracting Technicians (Private Method Test) ---");
    const technicians = (extractor as any).extractTechnicians(mockText);
    console.log("Technicians Found:", technicians.length);
    console.table(technicians);

    if (terpenes.length === 3 && terpenes[0].analyte === 'Beta-Myrcene') {
        console.log("✅ Terpene Extraction Logic: PASS");
    } else {
        console.error("❌ Terpene Extraction Logic: FAIL");
    }



    if (sampleInfo.sample_type === 'Distillate' && sampleInfo.moisture_content === 12.5 && sampleInfo.water_activity === 0.55 && sampleInfo.unit_mass_g === 11.5) {
        console.log("✅ Sample Info Extraction Logic: PASS");
    } else {
        console.log("Expected Unit Mass: 11.5, Got: ", sampleInfo.unit_mass_g);
        console.error("❌ Sample Info Extraction Logic: FAIL");
    }

    if (technicians.length === 2 && technicians[0].name === 'Alex Morris' && technicians[1].name === 'Nicholas Howard') {
        // 4. Test Client Info Extraction
        console.log('\n--- Extracting Client Info (Private Method Test) ---');
        // Access private method using 'any' cast
        const clientInfo = (extractor as any).extractClientInfo(mockText);
        if (clientInfo) {
            console.log('Client Info Found:', clientInfo);
        } else {
            console.error('❌ Client Info Not Found');
        }

        console.log('✅ Terpene Extraction Logic: PASS');
        console.log('✅ Sample Info Extraction Logic: PASS');
        console.log('✅ Technician Extraction Logic: PASS');
        console.log('✅ Client Info Extraction Logic: ' + (clientInfo ? 'PASS' : 'FAIL'));
    } else {
        console.error("❌ Technician Extraction Logic: FAIL");
    }
}


testKCAExtraction().catch(console.error);
